import type { Landmark, FrequencyDataPoint } from './types'

export const VIETNAM_LANDMARKS: Landmark[] = [
  {
    id: 'hoan-kiem',
    name: 'Hồ Hoàn Kiếm',
    nameEn: 'Hoan Kiem Lake',
    province: 'Hà Nội',
    lat: 21.0285,
    lng: 105.8542,
    category: 'temple',
    credibilityScore: 98,
    sources: 7,
    sourceVerified: true,
    description: 'Iconic lake in the heart of Hanoi with Ngoc Son Temple on a small island.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 1.5,
    indoor: false,
  },
  {
    id: 'ha-long-bay',
    name: 'Vịnh Hạ Long',
    nameEn: 'Ha Long Bay',
    province: 'Quảng Ninh',
    lat: 20.9101,
    lng: 107.1839,
    category: 'nature',
    credibilityScore: 99,
    sources: 9,
    sourceVerified: true,
    description: 'UNESCO World Heritage Site with thousands of limestone islands rising from emerald waters.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 8,
    indoor: false,
  },
  {
    id: 'hoi-an-old-town',
    name: 'Phố Cổ Hội An',
    nameEn: 'Hoi An Ancient Town',
    province: 'Quảng Nam',
    lat: 15.8801,
    lng: 108.338,
    category: 'museum',
    credibilityScore: 97,
    sources: 8,
    sourceVerified: true,
    description: 'A UNESCO-listed ancient trading port with lantern-lit streets and tailored clothing.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 4,
    indoor: false,
  },
  {
    id: 'phong-nha-cave',
    name: 'Hang Sơn Đoòng',
    nameEn: 'Son Doong Cave',
    province: 'Quảng Bình',
    lat: 17.4585,
    lng: 106.2863,
    category: 'cave',
    credibilityScore: 95,
    sources: 6,
    sourceVerified: true,
    description: 'Largest cave in the world with its own river, jungle, and weather system.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 6,
    indoor: true,
  },
  {
    id: 'ben-thanh-market',
    name: 'Chợ Bến Thành',
    nameEn: 'Ben Thanh Market',
    province: 'TP. Hồ Chí Minh',
    lat: 10.7726,
    lng: 106.698,
    category: 'market',
    credibilityScore: 91,
    sources: 5,
    sourceVerified: true,
    description: 'Iconic market in central Saigon selling street food, souvenirs, and local goods.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 2,
    indoor: true,
  },
  {
    id: 'my-son-sanctuary',
    name: 'Thánh Địa Mỹ Sơn',
    nameEn: 'My Son Sanctuary',
    province: 'Quảng Nam',
    lat: 15.7763,
    lng: 108.1199,
    category: 'temple',
    credibilityScore: 89,
    sources: 4,
    sourceVerified: true,
    description: 'UNESCO-listed Hindu temple complex built by the Cham civilization.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 3,
    indoor: false,
  },
  {
    id: 'mui-ne-sand-dunes',
    name: 'Đồi Cát Mũi Né',
    nameEn: 'Mui Ne Sand Dunes',
    province: 'Bình Thuận',
    lat: 10.9382,
    lng: 108.2878,
    category: 'nature',
    credibilityScore: 82,
    sources: 4,
    sourceVerified: true,
    description: 'Spectacular red and white sand dunes on the southern coast.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 2.5,
    indoor: false,
  },
  {
    id: 'tam-coc',
    name: 'Tràng An – Tam Cốc',
    nameEn: 'Trang An – Tam Coc',
    province: 'Ninh Bình',
    lat: 20.2181,
    lng: 105.913,
    category: 'nature',
    credibilityScore: 94,
    sources: 7,
    sourceVerified: true,
    description: 'Scenic boat rides through limestone karst landscapes and cave tunnels.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 4,
    indoor: false,
  },
  {
    id: 'da-lat-flower-garden',
    name: 'Vườn Hoa Đà Lạt',
    nameEn: 'Da Lat Flower Garden',
    province: 'Lâm Đồng',
    lat: 11.9419,
    lng: 108.4313,
    category: 'nature',
    credibilityScore: 76,
    sources: 3,
    sourceVerified: false,
    description: 'Vibrant flower park in the "City of Eternal Spring" highlands.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 2,
    indoor: false,
  },
  {
    id: 'sapa-rice-terraces',
    name: 'Ruộng Bậc Thang Sapa',
    nameEn: 'Sapa Rice Terraces',
    province: 'Lào Cai',
    lat: 22.3363,
    lng: 103.8448,
    category: 'nature',
    credibilityScore: 93,
    sources: 6,
    sourceVerified: true,
    description: 'Spectacular terraced rice fields carved into the mountains of northwest Vietnam.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 5,
    indoor: false,
  },
]

export const FREQUENCY_DATA: FrequencyDataPoint[] = [
  { province: 'Hà Nội', landmarks: 47, avgCredibility: 88, facebookHits: 1240, googleMapsHits: 980, blogHits: 620 },
  { province: 'TP. Hồ Chí Minh', landmarks: 52, avgCredibility: 85, facebookHits: 1580, googleMapsHits: 1120, blogHits: 740 },
  { province: 'Quảng Nam', landmarks: 28, avgCredibility: 91, facebookHits: 840, googleMapsHits: 760, blogHits: 520 },
  { province: 'Quảng Ninh', landmarks: 21, avgCredibility: 94, facebookHits: 960, googleMapsHits: 880, blogHits: 410 },
  { province: 'Ninh Bình', landmarks: 15, avgCredibility: 89, facebookHits: 620, googleMapsHits: 540, blogHits: 380 },
  { province: 'Lào Cai', landmarks: 18, avgCredibility: 87, facebookHits: 720, googleMapsHits: 610, blogHits: 430 },
  { province: 'Quảng Bình', landmarks: 12, avgCredibility: 82, facebookHits: 480, googleMapsHits: 390, blogHits: 280 },
  { province: 'Lâm Đồng', landmarks: 22, avgCredibility: 78, facebookHits: 560, googleMapsHits: 480, blogHits: 310 },
]
