import type { Landmark, FrequencyDataPoint, Creator, TravelPlan, AiServiceTier, Review } from './types'

export const VIETNAM_LANDMARKS: Landmark[] = [
  {
    id: 'hoan-kiem',
    name: 'Hồ Hoàn Kiếm',
    nameEn: 'Hoan Kiem Lake',
    province: 'Hà Nội',
    lat: 21.0285,
    lng: 105.8542,
    category: 'temple',
    credibilityScore: 98,
    sources: 7,
    sourceVerified: true,
    description: 'Iconic lake in the heart of Hanoi with Ngoc Son Temple on a small island.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 1.5,
    indoor: false,
  },
  {
    id: 'ha-long-bay',
    name: 'Vịnh Hạ Long',
    nameEn: 'Ha Long Bay',
    province: 'Quảng Ninh',
    lat: 20.9101,
    lng: 107.1839,
    category: 'nature',
    credibilityScore: 99,
    sources: 9,
    sourceVerified: true,
    description: 'UNESCO World Heritage Site with thousands of limestone islands rising from emerald waters.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 8,
    indoor: false,
  },
  {
    id: 'hoi-an-old-town',
    name: 'Phố Cổ Hội An',
    nameEn: 'Hoi An Ancient Town',
    province: 'Quảng Nam',
    lat: 15.8801,
    lng: 108.338,
    category: 'museum',
    credibilityScore: 97,
    sources: 8,
    sourceVerified: true,
    description: 'A UNESCO-listed ancient trading port with lantern-lit streets and tailored clothing.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 4,
    indoor: false,
  },
  {
    id: 'phong-nha-cave',
    name: 'Hang Sơn Đoòng',
    nameEn: 'Son Doong Cave',
    province: 'Quảng Bình',
    lat: 17.4585,
    lng: 106.2863,
    category: 'cave',
    credibilityScore: 95,
    sources: 6,
    sourceVerified: true,
    description: 'Largest cave in the world with its own river, jungle, and weather system.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 6,
    indoor: true,
  },
  {
    id: 'ben-thanh-market',
    name: 'Chợ Bến Thành',
    nameEn: 'Ben Thanh Market',
    province: 'TP. Hồ Chí Minh',
    lat: 10.7726,
    lng: 106.698,
    category: 'market',
    credibilityScore: 91,
    sources: 5,
    sourceVerified: true,
    description: 'Iconic market in central Saigon selling street food, souvenirs, and local goods.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 2,
    indoor: true,
  },
  {
    id: 'my-son-sanctuary',
    name: 'Thánh Địa Mỹ Sơn',
    nameEn: 'My Son Sanctuary',
    province: 'Quảng Nam',
    lat: 15.7763,
    lng: 108.1199,
    category: 'temple',
    credibilityScore: 89,
    sources: 4,
    sourceVerified: true,
    description: 'UNESCO-listed Hindu temple complex built by the Cham civilization.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 3,
    indoor: false,
  },
  {
    id: 'mui-ne-sand-dunes',
    name: 'Đồi Cát Mũi Né',
    nameEn: 'Mui Ne Sand Dunes',
    province: 'Bình Thuận',
    lat: 10.9382,
    lng: 108.2878,
    category: 'nature',
    credibilityScore: 82,
    sources: 4,
    sourceVerified: true,
    description: 'Spectacular red and white sand dunes on the southern coast.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 2.5,
    indoor: false,
  },
  {
    id: 'tam-coc',
    name: 'Tràng An – Tam Cốc',
    nameEn: 'Trang An – Tam Coc',
    province: 'Ninh Bình',
    lat: 20.2181,
    lng: 105.913,
    category: 'nature',
    credibilityScore: 94,
    sources: 7,
    sourceVerified: true,
    description: 'Scenic boat rides through limestone karst landscapes and cave tunnels.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 4,
    indoor: false,
  },
  {
    id: 'da-lat-flower-garden',
    name: 'Vườn Hoa Đà Lạt',
    nameEn: 'Da Lat Flower Garden',
    province: 'Lâm Đồng',
    lat: 11.9419,
    lng: 108.4313,
    category: 'nature',
    credibilityScore: 76,
    sources: 3,
    sourceVerified: false,
    description: 'Vibrant flower park in the "City of Eternal Spring" highlands.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 2,
    indoor: false,
  },
  {
    id: 'sapa-rice-terraces',
    name: 'Ruộng Bậc Thang Sapa',
    nameEn: 'Sapa Rice Terraces',
    province: 'Lào Cai',
    lat: 22.3363,
    lng: 103.8448,
    category: 'nature',
    credibilityScore: 93,
    sources: 6,
    sourceVerified: true,
    description: 'Spectacular terraced rice fields carved into the mountains of northwest Vietnam.',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    duration: 5,
    indoor: false,
  },
]

export const FREQUENCY_DATA: FrequencyDataPoint[] = [
  { province: 'Hà Nội', landmarks: 47, avgCredibility: 88, facebookHits: 1240, googleMapsHits: 980, blogHits: 620 },
  { province: 'TP. Hồ Chí Minh', landmarks: 52, avgCredibility: 85, facebookHits: 1580, googleMapsHits: 1120, blogHits: 740 },
  { province: 'Quảng Nam', landmarks: 28, avgCredibility: 91, facebookHits: 840, googleMapsHits: 760, blogHits: 520 },
  { province: 'Quảng Ninh', landmarks: 21, avgCredibility: 94, facebookHits: 960, googleMapsHits: 880, blogHits: 410 },
  { province: 'Ninh Bình', landmarks: 15, avgCredibility: 89, facebookHits: 620, googleMapsHits: 540, blogHits: 380 },
  { province: 'Lào Cai', landmarks: 18, avgCredibility: 87, facebookHits: 720, googleMapsHits: 610, blogHits: 430 },
  { province: 'Quảng Bình', landmarks: 12, avgCredibility: 82, facebookHits: 480, googleMapsHits: 390, blogHits: 280 },
  { province: 'Lâm Đồng', landmarks: 22, avgCredibility: 78, facebookHits: 560, googleMapsHits: 480, blogHits: 310 },
]

// ─── Business Model Mock Data ─────────────────────────────────────────────

export const MOCK_CREATORS: Creator[] = [
  {
    id: 'creator-1',
    name: 'Minh Tuan Nguyen',
    avatar: 'MT',
    bio: 'Backpacker turned professional travel planner. 8 years exploring every corner of Vietnam.',
    province: 'Hà Nội',
    totalPlans: 14,
    totalSales: 342,
    rating: 4.9,
    verified: true,
    joinedYear: 2022,
    platformCut: 15,
  },
  {
    id: 'creator-2',
    name: 'Linh Phuong Tran',
    avatar: 'LP',
    bio: 'Food blogger and cultural explorer. Specializing in central Vietnam hidden gems.',
    province: 'Đà Nẵng',
    totalPlans: 9,
    totalSales: 218,
    rating: 4.8,
    verified: true,
    joinedYear: 2023,
    platformCut: 15,
  },
  {
    id: 'creator-3',
    name: 'Duc Anh Le',
    avatar: 'DA',
    bio: 'Adventure travel guide. Specializing in northern highlands and trekking routes.',
    province: 'Lào Cai',
    totalPlans: 6,
    totalSales: 97,
    rating: 4.7,
    verified: false,
    joinedYear: 2024,
    platformCut: 15,
  },
  {
    id: 'creator-4',
    name: 'Thu Ha Vo',
    avatar: 'TH',
    bio: 'Luxury travel curator. Crafting premium itineraries with exclusive local experiences.',
    province: 'TP. Hồ Chí Minh',
    totalPlans: 11,
    totalSales: 189,
    rating: 4.9,
    verified: true,
    joinedYear: 2023,
    platformCut: 15,
  },
]

const BASE_STOPS_HANOI = [
  {
    landmark: VIETNAM_LANDMARKS[0],
    order: 1, travelTime: 0, transportMode: 'walk' as const,
    notes: 'Start at dawn before crowds. Ngoc Son Temple opens at 8 AM.',
  },
  {
    landmark: VIETNAM_LANDMARKS[7],
    order: 2, travelTime: 145, transportMode: 'taxi' as const,
    notes: 'Book boat tours in advance. Bring cash for tips.',
  },
]

const BASE_STOPS_SOUTH = [
  {
    landmark: VIETNAM_LANDMARKS[4],
    order: 1, travelTime: 0, transportMode: 'walk' as const,
    notes: 'Arrive early to avoid the afternoon heat. Try the bánh mì stalls at the entrance.',
  },
  {
    landmark: VIETNAM_LANDMARKS[6],
    order: 2, travelTime: 240, transportMode: 'bus' as const,
    notes: 'Best at sunrise or sunset. Rent a quad bike at the dunes.',
  },
]

export const MOCK_PLANS: TravelPlan[] = [
  {
    id: 'plan-1',
    title: '5-Day Classic North Vietnam',
    titleVi: '5 Ngày Bắc Việt Nam Cổ Điển',
    creator: MOCK_CREATORS[0],
    price: 12.99,
    originalPrice: 19.99,
    rating: 4.9,
    reviewCount: 87,
    purchaseCount: 214,
    province: 'Hà Nội',
    provinces: ['Hà Nội', 'Quảng Ninh', 'Ninh Bình'],
    duration: 5,
    difficulty: 'easy',
    category: 'cultural',
    coverImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    highlights: ['Hoan Kiem Lake at sunrise', 'Ha Long Bay overnight cruise', 'Tam Coc boat tour', 'Hanoi street food walk', 'Hidden temples & pagodas'],
    highlightsVi: ['Hồ Hoàn Kiếm lúc bình minh', 'Ngủ đêm trên thuyền Hạ Long', 'Chèo thuyền Tam Cốc', 'Khám phá ẩm thực đường phố Hà Nội', 'Đền chùa ẩn'],
    stops: BASE_STOPS_HANOI,
    aiVerified: true,
    factChecked: true,
    includesTransport: true,
    includesTips: true,
    includesMedia: true,
    createdAt: '2025-11-10',
    updatedAt: '2026-01-22',
    tags: ['Cultural', 'Beginner-Friendly', 'Best Seller', 'UNESCO'],
    shared: false,
  },
  {
    id: 'plan-2',
    title: '3-Day Hoi An & My Son Deep Dive',
    titleVi: '3 Ngày Hội An & Mỹ Sơn',
    creator: MOCK_CREATORS[1],
    price: 8.99,
    rating: 4.8,
    reviewCount: 54,
    purchaseCount: 128,
    province: 'Quảng Nam',
    provinces: ['Quảng Nam', 'Đà Nẵng'],
    duration: 3,
    difficulty: 'easy',
    category: 'cultural',
    coverImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    highlights: ['Ancient Town lantern festival', 'My Son Sanctuary at dusk', 'Tailoring streets', 'Local cooking class', 'Beach day at An Bang'],
    highlightsVi: ['Lễ hội đèn lồng Phố Cổ', 'Thánh địa Mỹ Sơn lúc hoàng hôn', 'Phố may đo', 'Lớp học nấu ăn địa phương', 'Nghỉ biển An Bàng'],
    stops: [],
    aiVerified: true,
    factChecked: true,
    includesTransport: true,
    includesTips: true,
    includesMedia: false,
    createdAt: '2025-12-05',
    updatedAt: '2026-02-01',
    tags: ['Cultural', 'UNESCO', 'Foodie', 'Photography'],
    shared: false,
  },
  {
    id: 'plan-3',
    title: '4-Day Sapa Highland Trek',
    titleVi: '4 Ngày Trekking Cao Nguyên Sapa',
    creator: MOCK_CREATORS[2],
    price: 14.99,
    rating: 4.7,
    reviewCount: 31,
    purchaseCount: 76,
    province: 'Lào Cai',
    provinces: ['Lào Cai'],
    duration: 4,
    difficulty: 'challenging',
    category: 'adventure',
    coverImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    highlights: ['Rice terrace sunrise hike', 'Muong Hoa Valley trail', 'H\'mong village homestay', 'Fansipan cable car', 'Night market in Sa Pa town'],
    highlightsVi: ['Leo núi ngắm ruộng bậc thang lúc bình minh', 'Đường mòn Thung lũng Mường Hoa', 'Ở nhà với người H\'Mông', 'Cáp treo Fansipan', 'Chợ đêm Sa Pa'],
    stops: [],
    aiVerified: true,
    factChecked: false,
    includesTransport: true,
    includesTips: true,
    includesMedia: true,
    createdAt: '2025-10-18',
    updatedAt: '2025-12-30',
    tags: ['Adventure', 'Trekking', 'Highlands', 'Homestay'],
    shared: false,
  },
  {
    id: 'plan-4',
    title: 'Luxury Saigon Weekend Getaway',
    titleVi: 'Cuối Tuần Xa Xỉ Tại Sài Gòn',
    creator: MOCK_CREATORS[3],
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.9,
    reviewCount: 62,
    purchaseCount: 141,
    province: 'TP. Hồ Chí Minh',
    provinces: ['TP. Hồ Chí Minh', 'Bình Thuận'],
    duration: 3,
    difficulty: 'easy',
    category: 'city',
    coverImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    highlights: ['Ben Thanh rooftop bar circuit', 'War Remnants Museum', 'Mui Ne day trip', 'Fine dining Vietnamese cuisine', 'Cu Chi Tunnels private tour'],
    highlightsVi: ['Bar rooftop quanh Bến Thành', 'Bảo tàng Chứng tích Chiến tranh', 'Tham quan Mũi Né trong ngày', 'Ẩm thực Việt Nam cao cấp', 'Tour riêng Địa đạo Củ Chi'],
    stops: BASE_STOPS_SOUTH,
    aiVerified: true,
    factChecked: true,
    includesTransport: true,
    includesTips: true,
    includesMedia: true,
    createdAt: '2025-09-14',
    updatedAt: '2026-02-10',
    tags: ['Luxury', 'City', 'Food', 'History'],
    shared: true,
  },
  {
    id: 'plan-5',
    title: 'Son Doong & Phong Nha Caves',
    titleVi: 'Hang Sơn Đoòng & Phong Nha',
    creator: MOCK_CREATORS[0],
    price: 22.99,
    rating: 4.8,
    reviewCount: 23,
    purchaseCount: 45,
    province: 'Quảng Bình',
    provinces: ['Quảng Bình'],
    duration: 4,
    difficulty: 'challenging',
    category: 'adventure',
    coverImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    highlights: ['World\'s largest cave', 'Underground jungle & river', 'Dark Cave zip-line', 'Phong Nha boat tour', 'Jungle camping'],
    highlightsVi: ['Hang lớn nhất thế giới', 'Rừng ngầm và sông ngầm', 'Trượt dây Dark Cave', 'Du thuyền Phong Nha', 'Cắm trại trong rừng'],
    stops: [],
    aiVerified: true,
    factChecked: true,
    includesTransport: false,
    includesTips: true,
    includesMedia: true,
    createdAt: '2026-01-05',
    updatedAt: '2026-02-20',
    tags: ['Adventure', 'Cave', 'UNESCO', 'Bucket List'],
    shared: false,
  },
  {
    id: 'plan-6',
    title: 'Da Lat Highlands Romantic Escape',
    titleVi: 'Lãng Mạn Đà Lạt Cao Nguyên',
    creator: MOCK_CREATORS[3],
    price: 9.99,
    rating: 4.6,
    reviewCount: 41,
    purchaseCount: 93,
    province: 'Lâm Đồng',
    provinces: ['Lâm Đồng'],
    duration: 3,
    difficulty: 'easy',
    category: 'nature',
    coverImage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-IsTxe4gOpp8hBejY9H5obJUpp8R74U.png',
    highlights: ['Flower Garden at bloom', 'Xuan Huong Lake sunrise', 'French colonial architecture', 'Valley of Love', 'Strawberry picking'],
    highlightsVi: ['Vườn hoa đang nở rộ', 'Bình minh hồ Xuân Hương', 'Kiến trúc thực dân Pháp', 'Thung lũng Tình yêu', 'Hái dâu tây'],
    stops: [],
    aiVerified: false,
    factChecked: false,
    includesTransport: true,
    includesTips: false,
    includesMedia: false,
    createdAt: '2025-08-22',
    updatedAt: '2025-11-15',
    tags: ['Nature', 'Romantic', 'Highlands', 'Budget-Friendly'],
    shared: false,
  },
]

export const AI_SERVICE_TIERS: AiServiceTier[] = [
  {
    id: 'per-plan',
    label: 'Per-Plan AI',
    labelVi: 'AI Theo Kế Hoạch',
    price: 2.99,
    priceLabel: 'per plan',
    memory: 'Isolated — no memory shared between plans',
    memoryVi: 'Độc lập — không chia sẻ bộ nhớ giữa các kế hoạch',
    context: 'Standard context (Gemini 1.5 Flash)',
    contextVi: 'Ngữ cảnh tiêu chuẩn (Gemini 1.5 Flash)',
    features: [
      'AI timeline polishing for this plan',
      'Currency exchange microservice',
      'Translation microservice',
      'Standard weather re-planning',
      'Fact-check verification badge',
    ],
    featuresVi: [
      'Tối ưu lịch trình AI cho kế hoạch này',
      'Dịch vụ chuyển đổi tiền tệ',
      'Dịch vụ dịch thuật',
      'Lập lại kế hoạch thời tiết tiêu chuẩn',
      'Huy hiệu xác minh thực tế',
    ],
  },
  {
    id: 'monthly',
    label: 'Monthly AI Subscription',
    labelVi: 'Đăng Ký AI Hàng Tháng',
    price: 9.99,
    priceLabel: '/ month',
    memory: 'Global — AI remembers preferences across all plans',
    memoryVi: 'Toàn cục — AI nhớ sở thích của bạn trên tất cả kế hoạch',
    context: 'Extended context (Gemini 1.5 Pro) with long history',
    contextVi: 'Ngữ cảnh mở rộng (Gemini 1.5 Pro) với lịch sử dài',
    features: [
      'All Per-Plan features on every plan',
      'Shared AI memory across all plans',
      'Unlimited real-time weather updates',
      'Live traffic & commotion alerts',
      'Extended context window (Gemini Pro)',
      'Priority AI response speed',
    ],
    featuresVi: [
      'Tất cả tính năng Per-Plan trên mọi kế hoạch',
      'Bộ nhớ AI dùng chung trên tất cả kế hoạch',
      'Cập nhật thời tiết thực tế không giới hạn',
      'Cảnh báo giao thông & sự cố trực tiếp',
      'Cửa sổ ngữ cảnh mở rộng (Gemini Pro)',
      'Tốc độ phản hồi AI ưu tiên',
    ],
    recommended: true,
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    user: 'Sarah K.',
    avatar: 'SK',
    rating: 5,
    comment: 'Absolutely incredible plan. Every detail was spot on, and the AI weather update saved us from a ruined boat tour day.',
    commentVi: 'Kế hoạch tuyệt vời. Mọi chi tiết đều chính xác, và cập nhật thời tiết AI đã cứu chuyến thuyền của chúng tôi.',
    date: '2026-01-15',
    helpful: 24,
  },
  {
    id: 'r2',
    user: 'James T.',
    avatar: 'JT',
    rating: 5,
    comment: 'Best travel plan I\'ve ever bought. The source-verified locations gave me real confidence. Highly recommend the monthly AI subscription.',
    commentVi: 'Kế hoạch du lịch tốt nhất tôi từng mua. Các địa điểm đã xác minh nguồn cho tôi sự tự tin thực sự. Đề xuất đăng ký AI hàng tháng.',
    date: '2025-12-28',
    helpful: 18,
  },
  {
    id: 'r3',
    user: 'Linh N.',
    avatar: 'LN',
    rating: 4,
    comment: 'Great overall but I wish there were more food recommendations. The Gap Fill AI feature filled in the blanks nicely.',
    commentVi: 'Nhìn chung rất tốt nhưng tôi ước có thêm gợi ý ẩm thực. Tính năng Gap Fill AI lấp đầy những chỗ trống rất tốt.',
    date: '2026-02-01',
    helpful: 9,
  },
]
